#!/usr/bin/env python
# encoding: utf-8

###############################################################################

import sys

def options(opt):
	pass

def configure(cfg):
	cfg.env.CXXFLAGS.append('-std=c++11')
	cfg.env.append_value('CXXFLAGS', '-g -rdynamic'.split()) # For debug.
	
	if cfg.check_cfg(package = 'opencv4', mandatory = False):
		opencv_package = 'opencv4'
	elif cfg.check_cfg(package = 'opencv3', mandatory = False):
		opencv_package = 'opencv3'
	elif cfg.check_cfg(package = 'opencv', mandatory = True):
		opencv_package = 'opencv'
	cfg.check_cfg(
		package = opencv_package,
		uselib_store = 'OpenCV',
		args = '--cflags --libs',
		mandatory = True
	)
		
def build(bld):
	bld.stlib(
		cxxflags = bld.env.CFLAGS_cshlib,
		source = bld.path.ant_glob('src/*.cpp'),
		includes = 'include',
		export_includes = 'include',
		use = 'OpenCV Utils',
		target = 'OpenCV_Utils'
	)

###############################################################################
