#!/usr/bin/env python
# encoding: utf-8

###############################################################################

import sys

def options(opt):
	pass

def configure(cfg):
	cfg.env.CXXFLAGS.append('-std=c++11')
	cfg.env.append_value('CXXFLAGS', '-g -rdynamic'.split()) # For debug.
		
def build(bld):
	bld.stlib(
		cxxflags = bld.env.CFLAGS_cshlib,
		source = bld.path.ant_glob('src/*.cpp'),
		includes = 'include',
		export_includes = 'include',
		target = 'Utils'
	)

###############################################################################
